+ cd /home/all_home/matias.joao/
+ module list
+ local _mlredir=0
+ '[' -n '' ']'
+ case " $@ " in
+ '[' 0 -eq 0 ']'
+ _module_raw list
++ /usr/bin/tclsh /usr/env-module/Modules5-3-1/libexec/modulecmd.tcl bash list
No Modulefiles Currently Loaded.
+ eval ''
+ _mlstatus=0
+ return 0
+ module avail
+ local _mlredir=0
+ '[' -n '' ']'
+ case " $@ " in
+ '[' 0 -eq 0 ']'
+ _module_raw avail
++ /usr/bin/tclsh /usr/env-module/Modules5-3-1/libexec/modulecmd.tcl bash avail
--------------------------- /opt/Modules/modulefiles ---------------------------
anaconda3.2023.09-0  cuda/12.3.2  modules      python3.10.12  
cuda/11.8.0          module-info  python3.7.6  python3.12.1   
+ eval ''
+ _mlstatus=0
+ return 0
+ module load python3.12.1
+ local _mlredir=0
+ '[' -n '' ']'
+ case " $@ " in
+ '[' 0 -eq 0 ']'
+ _module_raw load python3.12.1
++ /usr/bin/tclsh /usr/env-module/Modules5-3-1/libexec/modulecmd.tcl bash load python3.12.1
+ eval '__MODULES_LMCONFLICT=python3.12.1\&python; export __MODULES_LMCONFLICT;
PATH=/opt/python/3-1-12/bin:/home/grad/si/22/aliciachaves/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/usr/env-module/Modules5-3-1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/opt/puppetlabs/bin:/usr/local/slurm/bin:/home/phocus4/anaconda3/bin; export PATH;
__MODULES_LMREFRESH=python3.12.1; export __MODULES_LMREFRESH;
_LMFILES_=/opt/Modules/modulefiles/python3.12.1; export _LMFILES_;
LOADEDMODULES=python3.12.1; export LOADEDMODULES;
alias python=python3.12;
test 0;'
++ __MODULES_LMCONFLICT='python3.12.1&python'
++ export __MODULES_LMCONFLICT
++ PATH=/opt/python/3-1-12/bin:/home/grad/si/22/aliciachaves/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/usr/env-module/Modules5-3-1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/opt/puppetlabs/bin:/usr/local/slurm/bin:/home/phocus4/anaconda3/bin
++ export PATH
++ __MODULES_LMREFRESH=python3.12.1
++ export __MODULES_LMREFRESH
++ _LMFILES_=/opt/Modules/modulefiles/python3.12.1
++ export _LMFILES_
++ LOADEDMODULES=python3.12.1
++ export LOADEDMODULES
++ alias python=python3.12
++ test 0
+ _mlstatus=0
+ return 0
+ source .venv/bin/activate
++ deactivate nondestructive
++ '[' -n '' ']'
++ '[' -n '' ']'
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
++ '[' -n '' ']'
++ unset VIRTUAL_ENV
++ unset VIRTUAL_ENV_PROMPT
++ '[' '!' nondestructive = nondestructive ']'
++ VIRTUAL_ENV=/home/all_home/matias.joao/.venv
++ export VIRTUAL_ENV
++ _OLD_VIRTUAL_PATH=/opt/python/3-1-12/bin:/home/grad/si/22/aliciachaves/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/usr/env-module/Modules5-3-1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/opt/puppetlabs/bin:/usr/local/slurm/bin:/home/phocus4/anaconda3/bin
++ PATH=/home/all_home/matias.joao/.venv/bin:/opt/python/3-1-12/bin:/home/grad/si/22/aliciachaves/.vscode-server/cli/servers/Stable-f1e16e1e6214d7c44d078b1f0607b2388f29d729/server/bin/remote-cli:/usr/env-module/Modules5-3-1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin:/opt/puppetlabs/bin:/usr/local/slurm/bin:/home/phocus4/anaconda3/bin
++ export PATH
++ '[' -n '' ']'
++ '[' -z '' ']'
++ _OLD_VIRTUAL_PS1=
++ PS1='(.venv) '
++ export PS1
++ VIRTUAL_ENV_PROMPT='(.venv) '
++ export VIRTUAL_ENV_PROMPT
++ '[' -n /bin/bash -o -n '' ']'
++ hash -r
+ jupyter nbconvert --to notebook --execute /home_cerberus/disk2/haniel.botelho/uploads/Downloads/physionet.org/files/eicu-crd/2.0/fluxograma.ipynb --output outfluxo298.ipynb
[NbConvertApp] Converting notebook /home_cerberus/disk2/haniel.botelho/uploads/Downloads/physionet.org/files/eicu-crd/2.0/fluxograma.ipynb to notebook
/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/grad/si/22/aliciachaves' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/home/grad/si/22/aliciachaves' is not a writable location, using a temp directory.
  warn("IPython parent '{0}' is not a writable location,"
Traceback (most recent call last):
  File "/home/all_home/matias.joao/.venv/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 420, in start
    self.convert_notebooks()
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 597, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 563, in convert_single_notebook
    output, resources = self.export_single_notebook(
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/nbconvertapp.py", line 487, in export_single_notebook
    output, resources = self.exporter.from_filename(
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/exporters/notebook.py", line 36, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 154, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/exporters/exporter.py", line 353, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/preprocessors/base.py", line 48, in __call__
    return self.preprocess(nb, resources)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 103, in preprocess
    self.preprocess_cell(cell, resources, index)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbconvert/preprocessors/execute.py", line 124, in preprocess_cell
    cell = self.execute_cell(cell, index, store_history=True)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df_filtered = df_filtered[~df_filtered['apacheadmissiondx'].str.contains('sepsis|septic', case=False, na=False)]
len(df_filtered)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:3805[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3804[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3805[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3806[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32mindex.pyx:167[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mindex.pyx:175[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/index_class_helper.pxi:70[0m, in [0;36mpandas._libs.index.Int64Engine._check_type[0;34m()[0m

[0;31mKeyError[0m: 'apacheadmissiondx'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[7], line 1[0m
[0;32m----> 1[0m df_filtered [38;5;241m=[39m df_filtered[[38;5;241m~[39m[43mdf_filtered[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mapacheadmissiondx[39;49m[38;5;124;43m'[39;49m[43m][49m[38;5;241m.[39mstr[38;5;241m.[39mcontains([38;5;124m'[39m[38;5;124msepsis|septic[39m[38;5;124m'[39m, case[38;5;241m=[39m[38;5;28;01mFalse[39;00m, na[38;5;241m=[39m[38;5;28;01mFalse[39;00m)]
[1;32m      2[0m [38;5;28mlen[39m(df_filtered)

File [0;32m/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/pandas/core/series.py:1121[0m, in [0;36mSeries.__getitem__[0;34m(self, key)[0m
[1;32m   1118[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_values[key]
[1;32m   1120[0m [38;5;28;01melif[39;00m key_is_scalar:
[0;32m-> 1121[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_get_value[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   1123[0m [38;5;66;03m# Convert generator to list before going through hashable part[39;00m
[1;32m   1124[0m [38;5;66;03m# (We will iterate through the generator there to check for slices)[39;00m
[1;32m   1125[0m [38;5;28;01mif[39;00m is_iterator(key):

File [0;32m/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/pandas/core/series.py:1237[0m, in [0;36mSeries._get_value[0;34m(self, label, takeable)[0m
[1;32m   1234[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_values[label]
[1;32m   1236[0m [38;5;66;03m# Similar to Index.get_value, but we do not fall back to positional[39;00m
[0;32m-> 1237[0m loc [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mindex[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mlabel[49m[43m)[49m
[1;32m   1239[0m [38;5;28;01mif[39;00m is_integer(loc):
[1;32m   1240[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_values[loc]

File [0;32m/home/all_home/matias.joao/.venv/lib/python3.10/site-packages/pandas/core/indexes/base.py:3812[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3807[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(casted_key, [38;5;28mslice[39m) [38;5;129;01mor[39;00m (
[1;32m   3808[0m         [38;5;28misinstance[39m(casted_key, abc[38;5;241m.[39mIterable)
[1;32m   3809[0m         [38;5;129;01mand[39;00m [38;5;28many[39m([38;5;28misinstance[39m(x, [38;5;28mslice[39m) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m casted_key)
[1;32m   3810[0m     ):
[1;32m   3811[0m         [38;5;28;01mraise[39;00m InvalidIndexError(key)
[0;32m-> 3812[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3813[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3814[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3815[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3816[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3817[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'apacheadmissiondx'

+ hostname
gorgona7
slurmstepd: error: _cgroup_procs_check: failed on path (null)/cgroup.procs: No such file or directory
slurmstepd: error: Cannot write to cgroup.procs for (null)
slurmstepd: error: Unable to move pid 3629886 to init root cgroup (null)
